Safely write APEL timestamp JSON
ALU-Schumacher/AUDITOR pull request #1038
Opened 2024-11-07 11:12 UTC by maxfischer2781

This PR adds an "atomic write" for the APEL timestamp JSON. This avoids an (admittedly rare) race where opening the JSON for writing but not actually writing the content due to shutdown would leave the file empty.

2024-11-07 13:37 UTC, dirksammel requested changes
Thanks for this PR!
Please have a look at the failing checks: add an entry to the changelog, re-organize the import blocks according to ruff, and the typo in the tests.

2024-11-07 13:37 UTC, dirksammel commented on plugins/apel/tests/test_utiliy.py
The file name and the import have a type: utiliy instead of utility

2024-11-08 08:40 UTC, maxfischer2781 commented
Should I fix the MyPy check for 3.8, seeing how [it will be deprecated anyway](https://github.com/ALU-Schumacher/AUDITOR/pull/1039)? It's simple enough to fix, just not sure if it's worth enshrining the old types.

2024-11-08 10:47 UTC, dirksammel approved these changes

2024-11-08 10:48 UTC, dirksammel commented
> Should I fix the MyPy check for 3.8, seeing how [it will be deprecated anyway](https://github.com/ALU-Schumacher/AUDITOR/pull/1039)? It's simple enough to fix, just not sure if it's worth enshrining the old types.

No, that's fine, thanks!

2024-11-08 10:48 UTC, merged